# Generated by Django 4.1.4 on 2023-01-31 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicIndicatorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('quarter', models.CharField(max_length=120, null=True)),
                ('period', models.CharField(max_length=120, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.country')),
                ('economic_indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.indicator')),
            ],
        ),
    ]
