# Generated by Django 4.1.4 on 2022-12-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash_and_Equivalents', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Current_Assets', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Fixed_Assets', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('LongTerm_Investments', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Total_Assets', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Current_Debt', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Current_Liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('LongTerm_Debt', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Total_Liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Equity', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Total_Equity', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Outstanding_Shares', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Operating_Income', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Income_on_Equity_Investments', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Net_Income', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Total_Net_Income', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Depreciation_and_Amortization', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Operating_Cash_Flow', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Capital_Expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Investing_Cash_Flow', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Total_Debt_Issued', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Total_Debt_Repaid', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Stock_Buyback', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Total_Dividends_Paid', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('Financing_Cash_Flow', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('period', models.CharField(max_length=120, null=True)),
                ('year', models.IntegerField(null=True)),
                ('quarter', models.CharField(max_length=120, null=True)),
                ('reporting_period', models.DateTimeField(null=True)),
                ('ticker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(db_column='type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.industry'),
        ),
    ]
