# Generated by Django 4.1.4 on 2022-12-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financials',
            options={'ordering': ['-period']},
        ),
    ]
